### ISSUE TITLE
Possibly unclear section of text

### ISSUE THREAD

**Issue by nickbearman** [dmahr1/ihatecoordinatesystems#3]
Hello,

Thanks for the website, it's great. 

In https://ihatecoordinatesystems.com/#correct-crs, I read this bit:
If the attributes suggest the dataset is in the USA, then there might a problem converting to/from 🇺🇸 Freedom Units 🇺🇸. 

I'm not clear what converting to/from US Freedom Units US mean. I don't work in the US, so might be missing some local knowledge!

Thanks!
Nick.

**Comment by dmahr1** [comment]
@nickbearman "US" should be rendering as an American flag emoji. This is a tongue-in-cheek reference to the use of imperial units e.g. feet instead of meters. 

But as I learned just now, flag emojis don't render on Windows, which is ridiculous and Microsoft deserves shame. I usually run Linux so I never noticed. As a stopgap, I've replaced the emojis with PNG images.

Can you verify that you see the flags now? If so, please close the issue.

**Comment by nickbearman** [comment]
Ah yes - I see. Makes much more sense now, thanks!

Yes, I can see the flags (Windows 10, Chrome).
